name: Build Stego Toolkit

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # Это позволит Windows и macOS собраться, даже если Linux упадет
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            output_name: stego-toolkit-linux
            asset_ext: ""
          - os: windows-latest
            output_name: stego-toolkit-windows
            asset_ext: ".exe"
          - os: macos-latest
            output_name: stego-toolkit-macos
            asset_ext: ""

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23' # Ставим версию посвежее

    # Исправленный блок установки зависимостей для Linux
    - name: Install Linux Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libwayland-dev libx11-dev libx11-xcb-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libvulkan-dev

    # Трюк с go mod tidy, чтобы починить зависимости на лету
    - name: Tidy and Download modules
      run: |
        go mod tidy
        go mod download

    - name: Build
      run: |
        go build -v -o build/${{ matrix.output_name }}${{ matrix.asset_ext }} ./cmd/main.go

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ matrix.output_name }}
        path: build/${{ matrix.output_name }}${{ matrix.asset_ext }}